FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY workerapp  /home/workerapp3

CMD chrt $scheduling /home/workerapp3 $cmdargs > /home/logs/workerapp3$sch.log 2>&1

# CMD /home/workerapp3 $cmdargs > /home/logs/workerapp3.log 2>&1
