FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY workerapp  /home/workerapp0

CMD chrt $scheduling /home/workerapp0 $cmdargs > /home/logs/workerapp0.log 2>&1

# CMD /home/workerapp0 $cmdargs > /home/logs/workerapp0.log 2>&1
