FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY workerapp  /home/workerapp5

CMD chrt $scheduling /home/workerapp5 $cmdargs > /home/logs/workerapp5$sch.log 2>&1

# CMD /home/workerapp5 $cmdargs > /home/logs/workerapp5.log 2>&1