FROM debian

#RUN apt-get update && apt-get install -y build-essential libcap-dev libnuma-dev  
RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY datagenerator  /home/datagenerator

CMD chrt $scheduling /home/datagenerator $cmdargs > /home/logs/datagenerator$sch.log 2>&1

# CMD /home/datagenerator $cmdargs > /home/logs/datagenerator.log 2>&1
