/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "pidlist.check" instead.
 */

#include <check.h>

#line 1 "pidlist.check"
#include "../../src/testPosix/pidlist.h"

START_TEST(create_list)
{
#line 4
	fail_unless(1==1, "Default test");


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, create_list);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
