version: '2'

services:
  main:
    container_name: preempt
#    image: anapsix/alpine-java:latest

    build:
      context: .
#      target: prod -- new in 3.4
#      dockerfile: Dockerfile
#      args:
#        builno: 1
#        gitcommithash: xxxxxx
#        shm_size: '500mb' 
# labels not supported
#      labels:
#       - "com.siemens.description=Dummy test container RT"
#       - "com.siemens.department=Research"
#    cap_add:
#      - ALL
#      - SYS_NICE
#    cap_drop:
#      - NET_ADMIN
#      - SYS_ADMIN

# docker swarm only
#    deploy: xxx

#    networks:
#      - overlay

#    privileged: true
#    restart: always
#    network_mode: host

#volumes:

#networks:
#  overlay:
