FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY WorkerApp  /home/workerapp7

CMD chrt $scheduling /home/workerapp7 $cmdargs > /home/logs/workerapp7$sch.log 2>&1

# CMD /home/workerapp7 $cmdargs > /home/logs/workerapp7.log 2>&1
