FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY WorkerApp  /home/workerapp9

CMD chrt $scheduling /home/workerapp9 $cmdargs > /home/logs/workerapp9$sch.log 2>&1

# CMD /home/workerapp9 $cmdargs > /home/logs/workerapp9.log 2>&1
