FROM debian

RUN mkdir /home/logs && \
    chmod 777 /home/logs

RUN mkdir /home/tmp && \
    chmod 777 /home/tmp

COPY WorkerApp  /home/workerapp6

CMD chrt $scheduling /home/workerapp6 $cmdargs > /home/logs/workerapp6$sch.log 2>&1

# CMD /home/workerapp6 $cmdargs > /home/logs/workerapp6.log 2>&1