schedstat.o: schedstat.c pidlist.c pidparm.c update.c manage.c jsmn.c pidparm.c
	gcc -g -pthread schedstat.c pidlist.c update.c manage.c jsmn.c pidparm.c -o schedstat.o -I ../include/ -lrttest -lcap -lnuma -L ../../build/

