.\"                                      Hey, EMACS: -*- nroff -*-
.TH SCHEDSTAT 8 "April 15, 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
schedstat \- static real-time container orchestrator
.SH SYNOPSIS
.B schedstat
.RI "[ \-bdfmP ] [\-a " proc " ] [\-c " clock " ] [\-i " intv " ] \
[\-l " loop " ] [\-n " cmd " ] [\-p " prio " ] [\-r " time " ] [\-s " cmd "] \
[\-w " time " ] [config.json]

.\" .SH DESCRIPTION
.\" This manual page documents briefly the
.\" .B schedstat commands.
.\" .PP
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, respectively.
.\" \fBschedstat\fP is a program that...
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes ('\-\-'). The specified config file defines container
orchestration and resource scheduling details.
.br
A summary of options is included below.
.\" For a complete description, see the Info files.
.TP
.B \-a, \-\-affinity[=PROC-SPLIT]
Divide the CGroups of containers and system betweeo 0-[PROC-SPLIT-1] and 
[PROC-SPLIT]-MAX_CPU.
All containers will run on the latter control group, while systems processes will
be moved to the former, where possible
.br
The cpu numbers are the same as shown in the 
.I processor
field in /proc/cpuinfo.  See numa(3) for more information on specifying CPU sets.
.TP
.B \-b
bind non-real-time processes of the same container to the settings of the real-time
task settings of the container. For example, if a container hosts a non-real-time
process which launches a real-time thread, this flag will bind the non-real-time
main process to the same affinity and resource limit settings.
.TP
.TP
.B \-c, \-\-clock=CLOCK
select clock
.br
0 = CLOCK_MONOTONIC (default)
.br
1 = CLOCK_REALTIME
.br
2 = CLOCK_PROCESS_CPUTIME_ID
.br
3 = CLOCK_THREAD_CPUTIME_ID
.TP
.B \-d
set the deadline overshoot scheduling flag for qualifying SCHED_DEADLINE listed
tasks. This will enable notification via SIGXCPU to the overshooting thread, that
the computation is exceeding its deadline.
.TP
.B \-f
force execution with critical parameters. This might be needed when, e.g. the 
period for the update task in SCHED_DEADLINE is set to 1ms. Such a small period
could cause a system overload and starve other processes.
.TP
.B \-i, \-\-interval=INTV
Set the base interval for the update thread(s) for process data acquisition in
microseconds (default is 5000us).
.TP
.B \-l, \-\-loops=LOOPS
Set the number of intervals after which the kernel memory is cheked for new PIDs
mathing the detection pattern. Default loop numer is 100.
.TP
.B \-m, \-\-mlockall
Lock current and future memory allocations to prevent the orchestrator from being
paged out
.TP
.B \-n [CMD]
use command line signaure detection. The optional CMD parameter specifies pid command
to look for when identifying cotainer daemons. Default command line parameter is 
bash.
.TP
.B \-p, \-\-prio=PRIO
Set the priority of the update thread. This value is real-time prio for SCHED_FIFO 
or SCHED_RR and  niceness for SCHED_OTHER, SCHED_NORMAL, SCHED_BATCH or SCHED_IDLE.
It has no meaning for SCHED_DEADLINE as there is no prioritized hierarichacal 
deadline scheduling available (yet).
.TP
.B \-P
enables thread scan for the matching PIDs to identify real-time children threads
as well.(used with -n)
.TP
.B \-\-policy=NAME
set the scheduler policy of the measurement threads
where NAME is one of: other, normal, batch, idle, fifo, rr, deadline
.TP
.B \-r, \-\-runtime=TIME
sets the orchestrators runtime in seconds. Might come in handy when performing some
scripted test executions.
.TP
.B \-s [CMD]
use shim PPID container detection. The optional CMD parameter specifies ppid command
to look for when identifying cotainer daemons. Default command line parameter is 
docker-containerd-shim.
.TP
.B \-w, TIME
sets the worst case execution time for the update thread, default is set to 100us.
(used with --policy=deadline)

.SH SEE ALSO
.BR numa (3),
.BR numactl (8),
.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.
.SH AUTHOR
schedstat was written by Florian Hofer <info@florianhofer.it>.

