FROM ubuntu:jammy

MAINTAINER Florian Hofer (info@florianhofer.it)

RUN apt-get update && \
		apt-get install -y wget sudo unzip libusb-1.0-0-dev procps tcpdump iproute2
	
# These specify the software versions to download
ENV CDS_VERSION="4.11.0.0"

# Compose download url "CoDeSys Control SL for linux"
ENV URL="https://store-archive.codesys.com/ftp_download/3S/LinuxSL/2302000005/$CDS_VERSION/CODESYS%20Control%20for%20Linux%20SL%20$CDS_VERSION.package"

# Download Control SL package -- extract *.deb installer -Control and -Codemeter (dependency) and install
RUN wget --output-document=/tmp/codesys.package $URL && \
		unzip -p /tmp/codesys.package '*codemeter*.deb' > /tmp/codemeter.deb && dpkg -i /tmp/codemeter.deb && \
		unzip -p /tmp/codesys.package '*codesyscontrol*.deb' > /tmp/codesys.deb && dpkg -i /tmp/codesys.deb

RUN rm -rf /var/lib/apt/lists/*

# Add the default startup script from CoDeSys
WORKDIR /opt/codesys/scripts
ADD startup_vplc.sh startup.sh
#ADD https://github.com/flhofer/real-time-containers/tree/uc3-codesys/test-monitor/usecase/uc3/container/startup_vplc.sh startup.sh

# Set these ports to be accessible by default
EXPOSE 11740 11743

# Entrypoint is service start
ENTRYPOINT ["/opt/codesys/scripts/startup.sh"]

