# version 4.14.0.0 is the newest atm, replace with image at need
FROM codesyscontrol_virtuallinux:4.14.0.0

LABEL maintainer="Florian Hofer (info@florianhofer.it)"

RUN apt-get update && \
		apt-get install -y tcpdump iproute2 && \
		rm -rf /var/lib/apt/lists/*
