FROM ubuntu:22.04

RUN apt-get update && \
	apt-get install -y --no-install-recommends gcc g++ make git check libsubunit-dev libjson-c-dev libnuma-dev libcap-dev libgsl-dev && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /home
CMD ["make", "-B"]
