FROM fedora:latest

RUN dnf update -y && \
	dnf install -y gcc g++ make git procps-ng check check-devel subunit-devel json-c-devel numactl-devel libcap-devel gsl-devel

WORKDIR /home
CMD ["make", "-B"]

