name: C/C++ CI

on: 
  push:
    branches: # Run when pushed to develop and master
      - master
      - develop
        
  schedule:
    - cron: "0 2 * * 0" # Run at 2am UTC on Sun

jobs:
  build_and_test:

    runs-on: ubuntu-18.04
          
    steps:
    - uses: actions/checkout@v2.0.0

    - name: "Install dependencies"
      run: |
            sudo apt-get update \
            && sudo apt-get install -y gcc make git check libsubunit-dev libjson-c-dev libnuma-dev libcap-dev libgsl-dev libgsl-dbg

    - name: "Build Orchestrator and Use cases"
      run: make
      env: 
        DEBUG: ${{ !endsWith(github.ref, '/master') }}
      
    - name: "Run and build test code - libcheck"
      run: make -B test

    - name: "mv binaries to new folder"
      run: |
        mkdir bin \
        && mv orchestrator check_test DataGenerator WorkerApp bin/

    - name: Upload result for job
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: bin/
