name: C/C++ CI

on: 
  push:
    branches: # Run when pushed to develop and master
      - master
      - develop
        
  schedule:
    - cron: "0 2 * * 0" # Run at 2am UTC on Sun

jobs:
  build_and_test:

    runs-on: ubuntu-18.04
          
    steps:
    - uses: actions/checkout@v2.0.0

    - name: "Install dependencies"
      run: |
            sudo apt-get update \
            && sudo apt-get install -y gcc make git check libsubunit-dev libjson-c-dev libnuma-dev libcap-dev

    - name: "Build Orchestrator and Use cases"
      run: make DEBUG=1
      
    - name: "Build and run test code - libcheck"
      run: make check COVERAGE=1 DEBUG=1
